name: example-app
description: A example app for prometheus monitoring demo
version: 0.1.0
#kubeVersion: ">=1.9.0"
keywords:
  - prometheus
  - http
  - go
home: https://github.com/atoato88/prometheus-monitoring-demo
sources:
  - https://github.com/brancz/prometheus-example-app
maintainers:
  - name: atoato88
    email: atoato88+github@gmail.com
